data:
  train_size: (256, 256)
  valid_size: (256, 256)
  train_num_workers: 6
  test_num_workers: 8
  batch_size: 10
  with_mask: True

loss:
  losses: [ "id", "triplet", "center" ]

test:
  remove_junk: True
  lambda_: 0.0
  infer_flag: False
#  vehicle_clf_model_path: './car_reid/checkpoints/resNet34.pth'

device: 'cuda'


