data:
  name: 'VERIWild'
  pkl_path: '../outputs/veriwild.pkl'
  train_size: (224, 224)
  valid_size: (224, 224)
  train_num_workers: 16
  test_num_workers: 16 
  batch_size: 256
  with_mask: True
  test_ext: '_3000'

train:
  epochs: 120

loss:
  losses: ["id", "triplet", "center", "local-triplet"]

test:
  remove_junk: False
  lambda_: 0.5
  device: "cuda"
  split: 100
  model_path: "../outputs/veriwild_b256_224_pven/model_120.pth"

scheduler:
  milestones: [40, 70]

device: 'cuda'
output_dir: '../outputs/veriwild_b256_224_pven/'

