data:
  name: 'VERIWild'
  pkl_path: '../outputs/veriwild.pkl'
  train_size: (256, 256)
  valid_size: (256, 256)
  train_num_workers: 32
  test_num_workers: 16
  batch_size: 128
  with_mask: True
  test_ext: '_3000'

train:
  epochs: 60

loss:
  losses: ["id", "triplet", "center", "local-triplet"]

test:
  remove_junk: False
  lambda_: 0.5
  device: "cuda"
  split: 500
  model_path: "../outputs/veriwild_b128_pven/model_60.pth"

scheduler:
    milestones: [30, 50]

device: 'cuda'
output_dir: '../outputs/veriwild_b128_pven/'

