data:
  pkl_path: '../outputs/veri776.pkl'
  train_size: (256, 256)
  valid_size: (256, 256)
  train_num_workers: 6
  test_num_workers: 6
  batch_size: 64
  with_mask: True

loss:
  losses: ["id", "triplet", "center", "local-triplet"]

test:
  remove_junk: True
  lambda_: 0.5

device: 'cuda'
output_dir: '../outputs/veri776_b64_pven/'

